# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "pong-rust"
version = "0.1.0"
authors = ["Kaan Karaoglu"]
license-file = "LICENSE.md"
edition = "2021"

[dependencies]
ggez = "0.9.3"
