# Game configuration

[window_mode]
width = 1000
height = 1000
maximized = true
fullscreen_type = "Windowed"
borderless = false
transparent = false
min_width = 500
min_height = 500
max_width = 1000
max_height = 1000
resizable = false
visible = true
resize_on_scale_factor_change = false

[window_setup]
title = "PONG!"
samples = "One"
vsync = true
icon = ""
srgb = true

[backend]
type = 'All'
