name: Build, lint and format
on: [ push ]

jobs:
  build-lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2

      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
          components: clippy

      - name: Build | Lint
        run: cargo clippy

      - name: Run Rustfmt
        run: cargo fmt --all -- --check
