name: Build, lint and format
on: [ push ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SDL2
        run: sudo apt-get install libsdl2-dev

      - name: Setup Rust
        uses: ATiltedTree/setup-rust@v1.0.5
        with:
          rust-version: stable
          components: clippy

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run Rustfmt
        run: cargo fmt --all -- --check
